// Automatically generated by astro-icon
// 5d1146fce1403eaa868e03b634b2344c76bc3c6d2f54cf35eddfa1428f019f20

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "add"
		| "arrow-left"
		| "arrow-right"
		| "beach"
		| "building"
		| "bus"
		| "call"
		| "chevron-down"
		| "chevron-right"
		| "close"
		| "credit-card"
		| "deck"
		| "distance"
		| "download"
		| "elevator"
		| "fb"
		| "handshake"
		| "history"
		| "ig"
		| "local-activity"
		| "mail"
		| "menu"
		| "pets"
		| "plane"
		| "pool"
		| "search"
		| "share"
		| "star"
		| "upload"
		| "warning"
		| "wifi"
		| "x";
}